M48
; DRILL file KiCad 10.0.5 date 2026-08-19T20:48:16
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-08-19T20:48:16+05:30
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.5
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.200
%
G90
G05
T1
X76.25Y-70.0
X76.75Y-130.25
X196.25Y-70.0
X196.25Y-130.25
M30
